### PR TITLE
fix case mismatch

### LINKED ISSUE #47: RuntimeException: Case mismatch between loaded and declared class names
Last update from 1.6.5 to 1.6.6 added the following line to services.yml:

```yml
liuggio_stats_d.sender.class: Liuggio\StatsdClient\Service\StatsdService
```

This throws a RuntimeException since: Case mismatch between loaded and declared class names: Liuggio\StatsdClient\Service\StatsdService vs Liuggio\StatsdClient\Service\StatsDService

Updating the line with uppercase D fixes the issue:

```yml
liuggio_stats_d.sender.class: Liuggio\StatsdClient\Service\StatsDService
```

### PR DESCRIPTION
**Pull request by ccMatrix**
fixes #47

### CODE REVIEW

**Comment by liuggio** [comment]
Thanks a lot!!

**Comment by liuggio** [comment]
ops I realized now that the client calls has lower case except this one... how can we proceed 
@dav-m85  and @ccMatrix  what do you think? 

1. accept this PR
2. modify client?

**Comment by ccMatrix** [comment]
I would suggest to accept this PR first to release a fixed client without the issue since this is more critical than the visual change of the class names.

Then you can update the codebase to a new "Statsd" naming if you wish to match the client naming. I personally do not have a preference over StatsD or Statsd.

**Comment by dav-m85** [comment]
ops missed that one. Totally agree with @ccMatrix :)

**Pull request merged**
