### PR TITLE
New concise service

### PR DESCRIPTION
**Pull request by dav-m85**
At lafourchette, we like when using a service is fast and concise, and container access is reduced to the minimum. That's why we felt right to add a new service which takes the same responsabilities as the factory and the client.

Added the documentation to detail how it works.

### CODE REVIEW

**Comment by liuggio** [comment]
I really like this

**Comment by liuggio** [comment]
do you think that moving the service into the library https://github.com/liuggio/statsd-php-client and adding test could be done?

**Comment by liuggio** [comment]
@dav-m85 is this merge-able?

**Comment by dav-m85** [comment]
Nope not anymore :) Forgot to remove the WIP flag. I'm merging it.

**Pull request merged**
