### PR TITLE
Updated dependencies to use AuthorizationChecker instead of SecurityC…

### PR DESCRIPTION
**Pull request by ZilKil**
…ontext

### CODE REVIEW

**Comment by liuggio** [comment]
Does it have compatibility with SF2?

**Comment by liuggio** [comment]
thanks for this...
This introduce a BC
we should create a new version WDYT?

**Comment by ZilKil** [comment]
This breaks backwards compatibility and does not support Symfony2. If it's possible, you should create new version for SF3.

Also, Travis configuration should be updated in order to successfully build SF3 version.

**Comment by liuggio** [comment]
is possible to provide a solution that support sf2 and sf3?

**Comment by garak** [comment]
The SecurityContext has been deprecated in Symfony 2.6, so the proposed solution is indeed compatible with current supported  versions of Symfony 2 (2.7 and 2.8)

**Comment by ZilKil** [comment]
I have reduced minimum required Symfony version to 2.7

**Comment by garak** [comment]
Closing in favor of #62

**Pull request closed without merging**
